
project_id = "kbtgrvncxhbnjfhsqwlj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600

[functions.submit-score]
verify_jwt = false
